from typing import List, Optional
from pydantic import BaseModel, Field


class TaskRequest(BaseModel):
    """
    Incoming task submitted by the user.
    """
    task: str = Field(
        ...,
        min_length=5,
        description="High-level task to be completed by the multi-agent system",
    )
    context: Optional[str] = Field(
        default=None,
        description="Optional supporting context for the task",
    )


class TaskPlan(BaseModel):
    """
    Structured plan generated by the planner agent.
    """
    steps: List[str] = Field(
        ...,
        description="Ordered list of task steps created by the planner agent",
    )


class AgentResult(BaseModel):
    """
    Standard output from an individual agent.
    """
    agent_name: str
    content: str
    status: str = "success"


class FinalResponse(BaseModel):
    """
    Final orchestrated system response returned to the user.
    """
    task: str
    plan_steps: List[str]
    research_output: Optional[str] = None
    analysis_output: Optional[str] = None
    review_output: Optional[str] = None
    final_answer: str
    status: str = "success"


class ErrorResponse(BaseModel):
    """
    Standard error payload for predictable failures.
    """
    status: str = "error"
    message: str